[PHP]
memory_limit = 6400M
upload_max_filesize = 6400M
post_max_size = 6400M
max_execution_time = 600
default_socket_timeout = 3600
request_terminate_timeout = 600

[opcache]
opcache.enable=${PHP_OPCACHE_ENABLE}
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
opcache.revalidate_freq=0
opcache.save_comments=1
