<?php

namespace App\StoryEngine\Levers;

use App\StoryEngine\FactionState;
use App\StoryEngine\Seed;

class EconomicPressureResolver
{
    /**
     * @param FactionState $faction
     * @return Seed[] New conflict seeds generated by economic pressure
     */
    public static function apply(FactionState $faction): array
    {
        $stress = $faction->economy->stressLevel();
        $seeds = [];

        if ($stress > 70) {
            // Desperate -> War for resources
            $seeds[] = new Seed(
                'RESOURCE_WAR', 
                'faction', 
                7 + floor(($stress - 70) / 10) // Severity increases with stress
            );
        } elseif ($stress > 40) {
            // Stressed -> Trade conflicts
            $seeds[] = new Seed(
                'TRADE_CONFLICT', 
                'city', 
                4
            );
        }

        return $seeds;
    }
}
