<?php

namespace App\StoryEngine\Services;

use Tuzy\Application\Narrative\LLM\Contracts\LLMProvider;
use Illuminate\Support\Facades\Log;

class FakeStoryLLMService implements LLMProvider
{
    public function generate(string $systemPrompt, string $userPrompt): array
    {
        Log::info("FakeStoryLLM Generating...");
        
        return [
            'title' => 'The Fake Chapter',
            'content' => "This is a fake chapter generated by the testing service. \n\n" .
                         "It proves that the integration flow works correctly without hitting the real AI.",
        ];
    }
}
