<?php

namespace App\Domains\Saga\Services;

use App\Models\WorldEvent;
use App\Domains\Saga\Enums\EpicEventType;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class LedgerNarrator
{
    private array $templates;
    private NarrativeDictionary $dictionary;

    public function __construct(NarrativeDictionary $dictionary)
    {
        $this->dictionary = $dictionary;
        $this->loadTemplates();
    }

    private function loadTemplates(): void
    {
        $path = app_path('Domains/Saga/Data/narrative_transition_templates.json');
        if (File::exists($path)) {
            $this->templates = json_decode(File::get($path), true);
        } else {
            $this->templates = [];
        }
    }

    /**
     * Generate a narrative description for a WorldEvent.
     */
    public function narrate(WorldEvent $event): ?string
    {
        // Allow personal events with lower magnitude
        $allowedTypes = [
            EpicEventType::STAGE_TRANSITION->value, 
            EpicEventType::WORLD_COLLAPSE->value,
            'personal_event',
            'terraform_event',
            'entropy_spike'
        ];

        if ($event->payload['magnitude'] < 0.5 && !in_array($event->type, $allowedTypes)) {
            return null;
        }

        // For personal events, the description is already generated by EncounterService
        if ($event->type === 'personal_event') {
            return $event->payload['description'] ?? null;
        }

        $type = $event->type;
        $payload = $event->payload;
        $templateKey = $this->resolveTemplateKey($event);

        if (isset($payload['description']) && $payload['description'] !== "Một sự kiện chấn động đã xảy ra.") {
            return $payload['description'];
        }

        if (!$templateKey) {
            return $this->fallbackNarrative($event);
        }

        $template = $this->getRandomTemplate($type, $templateKey, $event->world);
        
        if (!$template) {
            return $this->fallbackNarrative($event);
        }

        return $this->fillPlaceholders($template, $event);
    }

    private function resolveTemplateKey(WorldEvent $event): ?string
    {
        $payload = $event->payload;

        if ($event->type === EpicEventType::STAGE_TRANSITION->value) {
            // e.g., "mundane" -> "mortal_martial" => "mundane_to_mortal_martial"
            $oldStage = $payload['old_stage'] ?? 'unknown';
            $newStage = $payload['new_stage'] ?? 'unknown';
            return "{$oldStage}_to_{$newStage}";
        }

        if ($event->type === EpicEventType::WORLD_COLLAPSE->value) {
            return $payload['reason_type'] ?? 'reason_perception';
        }

        // Mapping for new Epic types to their default/requested subtypes
        $typeDefaults = [
            EpicEventType::MYTH_BIRTH->value => 'artifact_discovery',
            EpicEventType::CATACLYSM->value => 'natural_disaster',
            EpicEventType::GREAT_WAR->value => 'clash_of_empires',
            EpicEventType::DIVINE_INTERVENTION->value => 'miracle',
            EpicEventType::ENTROPY_SPIKE->value => 'standard',
            EpicEventType::TERRAFORM_EVENT->value => 'reality_drift',
        ];

        if (array_key_exists($event->type, $typeDefaults)) {
            return $payload['subtype'] ?? $typeDefaults[$event->type];
        }

        return null;
    }

    private function getRandomTemplate(string $category, string $key, \App\Models\World $world): ?string
    {
        if (!isset($this->templates[$category][$key])) {
            return null;
        }

        $options = $this->templates[$category][$key];

        // Check for specific flavor based on World Type
        $flavor = strtolower($world->type->value ?? 'wuxia'); // Default to Wuxia if type is missing
        
        // If options is an associative array with flavor keys
        if (is_array($options) && array_keys($options) !== range(0, count($options) - 1)) {
            if (isset($options[$flavor])) {
                $options = $options[$flavor];
            } elseif (isset($options['default'])) {
                $options = $options['default'];
            } else {
                // Fallback to the first available flavor or specific key like 'wuxia'
                $options = reset($options);
            }
        }

        // Now $options should be a list of strings
        if (empty($options) || !is_array($options)) {
            return null;
        }

        return $options[array_rand($options)];
    }

    private function fillPlaceholders(string $template, WorldEvent $event): string
    {
        $world = $event->world;
        $location = "Trung tâm thế giới"; // Default, requires Location service for specificity

        // Simple replacements
        $replacements = [
            '{world_name}' => $world->name ?? 'Thế giới',
            '{location}' => $location,
            '{magnitude}' => $event->payload['magnitude'] ?? 0,
        ];

        return str_replace(array_keys($replacements), array_values($replacements), $template);
    }

    private function fallbackNarrative(WorldEvent $event): string
    {
        return $event->payload['description'] ?? "Một sự kiện chấn động đã xảy ra.";
    }
}
