<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Tuzy\Domain\Material\Contracts\MaterialRepositoryInterface;
use Tuzy\Application\Material\Extraction\MaterialValidator;
use Illuminate\Support\Facades\File;

class MaterialSeeder extends Seeder
{
    public function run(MaterialRepositoryInterface $repository): void
    {
        $materials = [
            // Domain 1: Economy/Survival
            [
                'code' => 'SUBSISTENCE_BASE',
                'ontology' => 'institutional',
                'function' => 'stabilizing',
                'default_lifecycle' => 'active',
                'description' => 'Foundation of food and resource production determining survival capacity. Low levels trigger famine risk, high levels enable population growth.',
                'origin_sources' => ['agricultural_systems', 'hunting_gathering', 'fishing_economies'],
                'pressure_inputs' => ['population' => 0.5, 'climate' => 0.5, 'technology' => 0.3],
                'pressure_outputs' => ['famine_risk' => -0.8, 'population_growth' => 0.6, 'expansion_pressure' => 0.4],
                'mutation_axes' => ['production_mode', 'resilience'],
            ],
            [
                'code' => 'RESOURCE_CONCENTRATION',
                'ontology' => 'institutional',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Degree of resource control by elites versus distributed access. High concentration drives elite emergence and class formation.',
                'origin_sources' => ['land_ownership', 'water_rights', 'mineral_control'],
                'pressure_inputs' => ['subsistence_base' => 0.4, 'labor_organization' => 0.6],
                'pressure_outputs' => ['elite_power' => 0.8, 'inequality' => 0.9, 'class_formation' => 0.7],
                'incompatible_with' => ['GIFT_ECONOMY', 'COMMUNAL_SHARING'],
                'mutation_axes' => ['concentration_level'],
            ],
            [
                'code' => 'SEASONAL_STABILITY',
                'ontology' => 'behavioral',
                'function' => 'stabilizing',
                'default_lifecycle' => 'active',
                'description' => 'Predictability of seasonal resource cycles. Low stability increases ritualization and prophecy demand.',
                'origin_sources' => ['climate_patterns', 'agricultural_cycles'],
                'pressure_inputs' => ['climate' => 0.9, 'subsistence_base' => 0.5],
                'pressure_outputs' => ['ritual_pressure' => -0.4, 'prophecy_demand' => -0.5, 'anxiety' => -0.6],
                'mutation_axes' => ['stability_level'],
            ],
            [
                'code' => 'LABOR_ORGANIZATION',
                'ontology' => 'institutional',
                'function' => 'stabilizing',
                'default_lifecycle' => 'active',
                'description' => 'How labor is organized and controlled. Variants include kin-based, coerced, and guild-like systems.',
                'origin_sources' => ['kinship_labor', 'slavery', 'corvee', 'guilds'],
                'pressure_inputs' => ['population' => 0.6, 'resource_concentration' => 0.5],
                'pressure_outputs' => ['rebellion_pressure' => 0.3, 'productivity' => 0.7, 'social_cohesion' => 0.4],
                'mutation_axes' => ['coercion_level', 'specialization'],
            ],
            [
                'code' => 'PRODUCTIVITY_CEILING',
                'ontology' => 'institutional',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Maximum output achievable with current technology and organization. Reaching ceiling triggers expansion or collapse.',
                'origin_sources' => ['technological_limits', 'organizational_capacity'],
                'pressure_inputs' => ['technology' => 0.8, 'labor_organization' => 0.5, 'specialization_depth' => 0.4],
                'pressure_outputs' => ['expansionism' => 0.6, 'collapse_risk' => 0.5, 'innovation_pressure' => 0.8],
                'mutation_axes' => ['ceiling_level'],
            ],
            [
                'code' => 'SPECIALIZATION_DEPTH',
                'ontology' => 'institutional',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Degree of labor specialization and interdependence. High specialization creates wealth but fragility.',
                'origin_sources' => ['craft_guilds', 'professional_classes'],
                'pressure_inputs' => ['productivity_ceiling' => 0.4, 'population' => 0.6],
                'pressure_outputs' => ['interdependence' => 0.9, 'fragility' => 0.7, 'wealth' => 0.8],
                'incompatible_with' => ['ISOLATION_MYTH', 'SELF_SUFFICIENCY'],
                'mutation_axes' => ['specialization_level'],
            ],
            [
                'code' => 'SURPLUS_DISTRIBUTION',
                'ontology' => 'institutional',
                'function' => 'stabilizing',
                'default_lifecycle' => 'active',
                'description' => 'How surplus resources are allocated. Variants include ritual redistribution, elite hoarding, and communal storage.',
                'origin_sources' => ['potlatch', 'tribute_systems', 'granaries'],
                'pressure_inputs' => ['subsistence_base' => 0.7, 'resource_concentration' => 0.6],
                'pressure_outputs' => ['unrest' => -0.5, 'legitimacy' => 0.6, 'inequality' => 0.4],
                'mutation_axes' => ['redistribution_mode'],
            ],
            [
                'code' => 'INEQUALITY_GRADIENT',
                'ontology' => 'institutional',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Steepness of wealth and power inequality. High gradients activate revolt myths and increase naturally without counter-myths.',
                'origin_sources' => ['class_systems', 'wealth_gaps'],
                'pressure_inputs' => ['resource_concentration' => 0.8, 'surplus_distribution' => -0.5],
                'pressure_outputs' => ['revolt_risk' => 0.9, 'myth_activation' => 0.7, 'social_tension' => 0.8],
                'incompatible_with' => ['EGALITARIAN_FOUNDING', 'COMMUNAL_EQUALITY'],
                'mutation_axes' => ['gradient_steepness'],
            ],
            [
                'code' => 'DEPENDENCY_CHAINS',
                'ontology' => 'institutional',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Length and complexity of resource dependency networks. Long chains create systemic fragility and cascade collapse risk.',
                'origin_sources' => ['trade_networks', 'supply_chains'],
                'pressure_inputs' => ['specialization_depth' => 0.7, 'trade_volume' => 0.6],
                'pressure_outputs' => ['systemic_fragility' => 0.8, 'collapse_cascade' => 0.9],
                'mutation_axes' => ['chain_length'],
            ],
            [
                'code' => 'FAMINE_TRIGGER',
                'ontology' => 'behavioral',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Activation of famine conditions causing population drop and belief mutation.',
                'origin_sources' => ['crop_failure', 'drought', 'war_disruption'],
                'preconditions' => ['subsistence_base' => 0.3], // < 0.3
                'pressure_inputs' => ['subsistence_base' => -0.9, 'seasonal_stability' => -0.7],
                'pressure_outputs' => ['population_drop' => 0.9, 'belief_mutation' => 0.7, 'migration' => 0.8],
            ],
            [
                'code' => 'RESOURCE_CONFLICT_PRESSURE',
                'ontology' => 'behavioral',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Pressure toward violent resource competition. Increases war likelihood and territorial expansion.',
                'origin_sources' => ['scarcity', 'competition'],
                'pressure_inputs' => ['subsistence_base' => -0.5, 'population' => 0.8, 'inequality_gradient' => 0.7],
                'pressure_outputs' => ['war_likelihood' => 0.9, 'territorial_expansion' => 0.7],
                'mutation_axes' => ['conflict_intensity'],
            ],
            [
                'code' => 'SURVIVAL_ADAPTATION',
                'ontology' => 'behavioral',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Cultural mutation in response to survival threats. Creates resilience and endurance narratives.',
                'origin_sources' => ['crisis_response', 'innovation'],
                'preconditions' => ['famine_trigger' => 0.5], // OR resource_conflict_pressure
                'pressure_inputs' => ['famine_trigger' => 0.8, 'resource_conflict_pressure' => 0.7],
                'pressure_outputs' => ['cultural_mutation' => 0.8, 'resilience' => 0.6],
                'mutation_axes' => ['adaptation_depth'],
            ],

            // Domain 5: Memory/Reinterpretation
            [
                'code' => 'CANONICAL_HISTORY',
                'ontology' => 'symbolic',
                'function' => 'stabilizing',
                'default_lifecycle' => 'dormant',
                'description' => 'Official, authorized version of historical narrative. High strength creates stable narrative, low creates competing versions.',
                'origin_sources' => ['official_chronicles', 'state_histories'],
                'preconditions' => ['authority' => 0.5],
                'pressure_inputs' => ['authority' => 0.8, 'institutional_education' => 0.7],
                'pressure_outputs' => ['narrative_stability' => 0.9, 'legitimacy' => 0.8],
                'mutation_axes' => ['canonicity_level'],
            ],
            [
                'code' => 'SELECTIVE_MEMORY',
                'ontology' => 'symbolic',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Systematic forgetting or suppression of inconvenient past. Creates denial, scapegoating, and taboo zones.',
                'origin_sources' => ['historical_denial', 'suppression'],
                'pressure_inputs' => ['trauma_encoding' => 0.7, 'political_pressure' => 0.6],
                'pressure_outputs' => ['denial' => 0.8, 'scapegoating' => 0.7, 'taboo_zones' => 0.9],
                'incompatible_with' => ['TRANSPARENCY_MYTH', 'TRUTH_SEEKING'],
                'mutation_axes' => ['suppression_depth'],
            ],
            [
                'code' => 'ORAL_WRITTEN_RATIO',
                'ontology' => 'institutional',
                'function' => 'stabilizing',
                'default_lifecycle' => 'active',
                'description' => 'Balance between oral tradition and written records. High oral creates fast myth drift, high written creates rigidity.',
                'origin_sources' => ['oral_tradition', 'written_chronicles', 'literacy'],
                'pressure_inputs' => ['literacy_rate' => 0.5, 'institutional_education' => 0.6],
                'pressure_outputs' => ['myth_drift_rate' => -0.7, 'narrative_flexibility' => -0.6],
                'mutation_axes' => ['oral_dominance'],
            ],
            [
                'code' => 'MYTH_REINTERPRETATION_PRESSURE',
                'ontology' => 'symbolic',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Force pushing historical events toward mythic/sacred interpretation. Creates sacred timelines.',
                'origin_sources' => ['sacralization', 'mythologization'],
                'preconditions' => ['symbolic_dominance' => 0.6],
                'pressure_inputs' => ['time_distance' => 0.8, 'ritual_pressure' => 0.7],
                'pressure_outputs' => ['sacralization' => 0.9, 'historical_distance' => 0.8],
                'mutation_axes' => ['mythologization_rate'],
            ],
            [
                'code' => 'HISTORICAL_REVISIONISM',
                'ontology' => 'symbolic',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Active rewriting of history for present political needs. Reforges legitimacy but creates narrative conflict.',
                'origin_sources' => ['propaganda', 'rewritten_chronicles'],
                'pressure_inputs' => ['political_pressure' => 0.9, 'legitimacy_crisis' => 0.8],
                'pressure_outputs' => ['legitimacy_reforge' => 0.7, 'narrative_conflict' => 0.9],
                'mutation_axes' => ['revision_depth'],
            ],
            [
                'code' => 'TRAUMA_ENCODING',
                'ontology' => 'symbolic',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'How collective trauma becomes embedded in cultural memory. Creates taboos, fear loops, and silence zones.',
                'origin_sources' => ['collective_trauma', 'catastrophe_memory'],
                'preconditions' => ['collapse' => 0.5], // OR famine
                'pressure_inputs' => ['famine_trigger' => 0.9, 'collapse_events' => 0.9],
                'pressure_outputs' => ['cultural_taboo' => 0.8, 'fear_loop' => 0.7, 'avoidance' => 0.9],
                'mutation_axes' => ['trauma_depth'],
            ],
            [
                'code' => 'RITUALIZED_REMEMBRANCE',
                'ontology' => 'behavioral',
                'function' => 'stabilizing',
                'default_lifecycle' => 'dormant',
                'description' => 'Regular ritual reenactment of historical events. Keeps past active and reinforces identity.',
                'origin_sources' => ['commemorations', 'reenactments', 'festivals'],
                'pressure_inputs' => ['ritual_strength' => 0.8, 'canonical_history' => 0.6],
                'pressure_outputs' => ['past_activation' => 0.9, 'identity_reinforcement' => 0.8],
                'mutation_axes' => ['ritual_frequency'],
            ],
            [
                'code' => 'GRIEVANCE_ACCUMULATION',
                'ontology' => 'behavioral',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Buildup of historical wrongs into active conflict motivation. Creates revenge cycles and eternal enemy narratives.',
                'origin_sources' => ['historical_injustice', 'unresolved_conflicts'],
                'pressure_inputs' => ['inequality_gradient' => 0.7, 'selective_memory' => 0.6],
                'pressure_outputs' => ['conflict_ignition' => 0.9, 'revenge_cycles' => 0.8],
                'mutation_axes' => ['grievance_depth'],
            ],
            [
                'code' => 'NOSTALGIA_PRESSURE',
                'ontology' => 'symbolic',
                'function' => 'transformative',
                'default_lifecycle' => 'dormant',
                'description' => 'Idealization of past leading to regressive policies. Creates resistance to change and lost golden age myths.',
                'origin_sources' => ['golden_age_myth', 'decline_narrative'],
                'pressure_inputs' => ['crisis' => 0.7, 'decline_perception' => 0.8],
                'pressure_outputs' => ['regression_policy' => 0.8, 'change_resistance' => 0.9],
                'incompatible_with' => ['PROGRESSIVE_MYTH', 'INNOVATION_CULT'],
                'mutation_axes' => ['nostalgia_intensity'],
            ],
            [
                'code' => 'IDENTITY_FOSSILIZATION',
                'ontology' => 'symbolic',
                'function' => 'destructive',
                'default_lifecycle' => 'dormant',
                'description' => 'Rigid crystallization of identity around historical memory. Very slow decay, creates cultural rigidity.',
                'origin_sources' => ['ethnic_memory', 'caste_systems'],
                'pressure_inputs' => ['trauma_encoding' => 0.8, 'canonical_history' => 0.7],
                'pressure_outputs' => ['change_resistance' => 0.95, 'cultural_rigidity' => 0.9],
                'mutation_axes' => ['fossilization_depth'],
            ],
        ];

        foreach ($materials as $data) {
            if ($repository->findByCode($data['code'])) {
                continue;
            }
            $repository->create($data);
        }
        
        $this->command->info('Core materials seeded successfully (Economy & Memory).');
    }
}
