apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldos.fullname" . }}-gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
  type: {{ .Values.gateway.service.type }}