apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldos.fullname" . }}-world-simulation
spec:
  selector:
    app: world-simulation
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
  type: ClusterIP