<?php

declare(strict_types=1);

namespace App\Modules\Narrative\Entities;

use App\Modules\Narrative\ValueObjects\ChapterStatus;
use DateTimeImmutable;
use LogicException;
use Ramsey\Uuid\Uuid;

/**
 * Serial Chapter Entity — unit of narrative text.
 *
 * From docs §11.2: raw_text generated by LLMChronicler,
 * goes through DRAFT → NEEDS_REVIEW → APPROVED → CANONIZED pipeline.
 *
 * Pure PHP — NO Eloquent.
 */
final class SerialChapterEntity
{
    public function __construct(
        private readonly string $id,
        private readonly string $seriesId,
        private readonly int $bookIndex,
        private readonly int $chapterIndex,
        private string $rawText,
        private ChapterStatus $status,
        private ?DateTimeImmutable $canonizedAt,
    ) {
    }

    public static function draft(
        string $seriesId,
        int $bookIndex,
        int $chapterIndex,
        string $rawText,
    ): self {
        return new self(
            id: Uuid::uuid4()->toString(),
            seriesId: $seriesId,
            bookIndex: $bookIndex,
            chapterIndex: $chapterIndex,
            rawText: $rawText,
            status: ChapterStatus::DRAFT,
            canonizedAt: null,
        );
    }

    // ── Getters ──

    public function getId(): string
    {
        return $this->id;
    }

    public function getSeriesId(): string
    {
        return $this->seriesId;
    }

    public function getBookIndex(): int
    {
        return $this->bookIndex;
    }

    public function getChapterIndex(): int
    {
        return $this->chapterIndex;
    }

    public function getRawText(): string
    {
        return $this->rawText;
    }

    public function getStatus(): ChapterStatus
    {
        return $this->status;
    }

    public function getCanonizedAt(): ?DateTimeImmutable
    {
        return $this->canonizedAt;
    }

    // ── Lifecycle Methods ──

    public function submitForReview(): void
    {
        if (!$this->status->canReview()) {
            throw new LogicException(
                "Cannot submit chapter [{$this->id}] for review: status is [{$this->status->value}]"
            );
        }

        $this->status = ChapterStatus::NEEDS_REVIEW;
    }

    public function approve(): void
    {
        if (!$this->status->canApprove()) {
            throw new LogicException(
                "Cannot approve chapter [{$this->id}]: status is [{$this->status->value}]"
            );
        }

        $this->status = ChapterStatus::APPROVED;
    }

    public function canonize(): void
    {
        if (!$this->status->canCanonize()) {
            throw new LogicException(
                "Cannot canonize chapter [{$this->id}]: status is [{$this->status->value}]"
            );
        }

        $this->status = ChapterStatus::CANONIZED;
        $this->canonizedAt = new DateTimeImmutable();
    }

    /**
     * Edit raw text (only allowed before canonization).
     */
    public function editText(string $newText): void
    {
        if ($this->status === ChapterStatus::CANONIZED) {
            throw new LogicException("Cannot edit canonized chapter [{$this->id}]");
        }

        $this->rawText = $newText;
    }
}
